/**
 * The §4.2 gaps §11.2's harness cannot check, checked against the golden
 * files directly.
 *
 * PROVENANCE. The numbers in `metrics.ts` were measured off two source PDFs
 * composed in Illustrator. Those PDFs carry real personal content, so they
 * are not distributable and `data/reference/` is gitignored — which means the
 * goldens committed here are *not* those measurements. They are generated by
 * rendering the example profile (`data/profiles/jordan-rivera`) and freezing
 * the result, so what this file verifies is agreement between `metrics.ts`
 * and the committed render, not fidelity to the original source.
 *
 * That is still worth gating. The goldens are frozen at commit time, so
 * changing a constant in `metrics.ts` without regenerating them fails here —
 * the same regression guard, minus the external provenance claim.
 *
 * The agreement is asserted at §11.2's ±2pt, not exactly. Chromium's laid-out
 * baselines sit a fraction below the measured constants (0.22pt at the name,
 * 0.77pt at the minimal contact line, 0.82pt at the full header's second
 * line) because the constants describe Illustrator's composition and the
 * render approximates it. Sub-point drift of exactly this size is what the
 * ±2pt tolerance exists to absorb; asserting equality to two decimals would
 * be asserting that the two composers agree perfectly, which they never did.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import {
  ABOUT_ME_SPACE_BEFORE_PT,
  NAME_BASELINE_TO_ABOUT_ME_PT,
  SPACE_BEFORE_PT,
} from "./metrics";

type GoldenItem = { page: number; text: string; baselineY: number };

function golden(file: string): GoldenItem[] {
  const path = join(process.cwd(), "harness", file);
  return (JSON.parse(readFileSync(path, "utf8")) as { items: GoldenItem[] }).items;
}

/** The first item whose text starts with `prefix` — texts are unique enough. */
function baselineOf(items: GoldenItem[], prefix: string): number {
  const item = items.find((candidate) => candidate.text.startsWith(prefix));
  if (!item) throw new Error(`no golden item starting with ${JSON.stringify(prefix)}`);
  return item.baselineY;
}

/** SPEC §11.2's fidelity tolerance — the same one the harness gates on. */
const TOLERANCE_PT = 2;

const detailed = golden("golden.json");
const basic = golden("golden-basic.json");

describe("About Me space-before (§4.2, measured)", () => {
  it("places the heading the measured distance below the name", () => {
    const gap = baselineOf(detailed, "Jordan A.") - baselineOf(detailed, "About Me");
    expect(Math.abs(gap - NAME_BASELINE_TO_ABOUT_ME_PT)).toBeLessThan(TOLERANCE_PT);
  });

  it("reproduces the minimal header's contact → heading gap", () => {
    const gap = baselineOf(detailed, "jordan.rivera@") - baselineOf(detailed, "About Me");
    expect(Math.abs(gap - ABOUT_ME_SPACE_BEFORE_PT.minimal)).toBeLessThan(TOLERANCE_PT);
  });

  it("keeps the section table and the About Me table saying the same thing", () => {
    expect(SPACE_BEFORE_PT.aboutMe).toBe(ABOUT_ME_SPACE_BEFORE_PT.minimal);
  });

  it("reproduces the full header's second-contact → heading gap", () => {
    const gap = baselineOf(basic, "linkedin.com/") - baselineOf(basic, "About Me");
    expect(Math.abs(gap - ABOUT_ME_SPACE_BEFORE_PT.full)).toBeLessThan(TOLERANCE_PT);
  });

  it("opens tighter under a full header than under a minimal one", () => {
    // The full header spends a whole extra line on contacts, so its last
    // contact line sits nearer the heading than the minimal header's does.
    const full = baselineOf(basic, "linkedin.com/") - baselineOf(basic, "About Me");
    const minimal = baselineOf(detailed, "jordan.rivera@") - baselineOf(detailed, "About Me");
    expect(full).toBeLessThan(minimal);
    expect(ABOUT_ME_SPACE_BEFORE_PT.full).toBeLessThan(ABOUT_ME_SPACE_BEFORE_PT.minimal);
  });
});

describe("Projects space-before (§4.2, bounded not measured)", () => {
  it("has no gap to measure at the top of a page — the heading opens page 2", () => {
    const heading = detailed.find((item) => item.text === "Projects");
    expect(heading?.page).toBe(2);
  });

  it("sits within §11.2's tolerance of both bullet-preceded gaps", () => {
    for (const section of ["education", "skills"] as const) {
      expect(Math.abs(SPACE_BEFORE_PT.projects - SPACE_BEFORE_PT[section])).toBeLessThan(
        TOLERANCE_PT,
      );
    }
  });
});
